import { mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const out = resolve(root, "src/generated/vendor-assets.ts");
const files = [
  "core/core.js",
  "core/core.wasm",
  "ffmpeg/bun-worker.js",
  "ffmpeg/const.js",
  "ffmpeg/errors.js",
  "ffmpeg/worker.js",
] as const;

const hash = createHash("sha256");
const entries = await Promise.all(files.map(async (relativePath) => {
  const bytes = Buffer.from(await Bun.file(resolve(root, "vendor", relativePath)).arrayBuffer());
  hash.update(relativePath);
  hash.update(bytes);
  return { relativePath, data: bytes.toString("base64") };
}));
const buildId = hash.digest("hex").slice(0, 16);

await mkdir(resolve(root, "src/generated"), { recursive: true });
await writeFile(out, `// Generated by scripts/generate-assets.ts. Do not edit by hand.\nexport const vendorAssetBuildId = ${JSON.stringify(buildId)};\nexport const vendorAssets = ${JSON.stringify(entries)} as const;\n`);
console.log(`Wrote ${out}`);
